name: dalelak_app
description: "A Flutter project showcasing tourist places in Jordan."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  # Adding dependencies for managing state, maps, and HTTP requests
  google_maps_flutter: ^2.9.0
  provider: ^6.0.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets for images
  assets:
    - assets/images/

  # Fonts can be added here if required for custom text styling
  # Example:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
